FROM python:3.12.4


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH "/home/python/app:/home/python/app"


WORKDIR /home/python/app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .


EXPOSE 8000

# CMD ["sh", "-c", "python src/migrates/create_table_chat.py && python src/migrates/create_table_memory.py && python src/migrates/create_table_vector_embedding.py && python src/data_ingestion/extract_chunks.py && uvicorn src.templates.default.fastapi.main:app --host 0.0.0.0 --port 8000"]
